TDServicesApp/TDServicesApp/Controllers/CloudController.cs
using log4net;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.Store.PartnerCenter;
using Microsoft.Store.PartnerCenter.Extensions;
using Microsoft.Store.PartnerCenter.Models.Auditing;
using Microsoft.Store.PartnerCenter.Models.Invoices;
using Microsoft.Store.PartnerCenter.Models.Query;
using Microsoft.Store.PartnerCenter.Models.ServiceCosts;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NtpClient;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using TDServicesApp.Models;

namespace TDServicesApp.Controllers
{
    [Authorize(Roles = "Admin, Demo")]
    public class CloudController : GlobalController
    {
        public ActionResult MSCSPRateCard()
        {
            IAggregatePartner partner = GetPartnerCenterTokenUsingAppCredentials();
            var model = new OfferView();
            List<object> azureRateCardAU = new List<object>();

            // Get the rate card (aka price list)
            var azureRateCard = partner.RateCards.Azure.Get();

            // Add columns to the DataTable object
            model.rateCardAU = new DataTable();
            model.rateCardAU.Columns.Add("Catagory", typeof(string));
            model.rateCardAU.Columns.Add("EffectiveDate", typeof(string));
            model.rateCardAU.Columns.Add("Id", typeof(string));
            model.rateCardAU.Columns.Add("IncludedQuantity", typeof(string));
            model.rateCardAU.Columns.Add("Names", typeof(string));
            model.rateCardAU.Columns.Add("Rates", typeof(string));
            model.rateCardAU.Columns.Add("Region", typeof(string));
            model.rateCardAU.Columns.Add("SubCatagory", typeof(string));
            model.rateCardAU.Columns.Add("Tags", typeof(string));
            model.rateCardAU.Columns.Add("Unit", typeof(string));

            foreach (var meter in azureRateCard.Meters)
            {
                if (meter.Region.StartsWith("AU"))
                {
                    azureRateCardAU.Add(meter);
                    var effectivedate = meter.EffectiveDate.ToString();
                    var rates = (String.Join(", ", meter.Rates.ToArray()).ToString());
                    var tags = (String.Join(", ", meter.Tags.ToArray()).ToString());
                    model.rateCardAU.Rows.Add(meter.Category, effectivedate, meter.Id, meter.IncludedQuantity, meter.Name, rates, meter.Region, meter.Subcategory, tags, meter.Unit);
                }
            }

            // Get all partner invoices
            var pagedInvoiceCollection = partner.Invoices.Query(QueryFactory.Instance.BuildIndexedQuery(5, 0));

            model.getDate = DateTime.Now.ToLocalTime();
            model.rateCardAUCount = azureRateCardAU.Count();

            return View(model);
        }

        public ActionResult MSCSPOffers()
        {
            IAggregatePartner partner = GetPartnerCenterTokenUsingAppCredentials();
            var model = new OfferView();
            List<object> azureRateCardAU = new List<object>();

            // Add columns to the DataTable object
            model.offerTable = new DataTable();
            model.offerTable.Columns.Add("Offer ID", typeof(string));
            model.offerTable.Columns.Add("Name", typeof(string));
            model.offerTable.Columns.Add("Description", typeof(string));
            model.offerTable.Columns.Add("Prerequisite Offers", typeof(string));
            model.offerTable.Columns.Add("Product ID", typeof(string));
            model.offerTable.Columns.Add("Product Name", typeof(string));
            model.offerTable.Columns.Add("UnitType", typeof(string));

            // Get a list of offers.
            var offers = partner.Offers.ByCountry("AU").Get();
            foreach (var offer in offers.Items)
            {
                var PrerequisiteOffers = String.Join(", ", offer.PrerequisiteOffers.ToArray());
                model.offerTable.Rows.Add(offer.Id, offer.Name, offer.Description, PrerequisiteOffers.ToString(), offer.Product.Id, offer.Product.Name, offer.UnitType);
            }

            // Get the rate card (aka price list)
            var azureRateCard = partner.RateCards.Azure.Get();

            // Add columns to the DataTable object
            model.rateCardAU = new DataTable();
            model.rateCardAU.Columns.Add("Catagory", typeof(string));
            model.rateCardAU.Columns.Add("EffectiveDate", typeof(string));
            model.rateCardAU.Columns.Add("Id", typeof(string));
            model.rateCardAU.Columns.Add("IncludedQuantity", typeof(string));
            model.rateCardAU.Columns.Add("Names", typeof(string));
            model.rateCardAU.Columns.Add("Rates", typeof(string));
            model.rateCardAU.Columns.Add("Region", typeof(string));
            model.rateCardAU.Columns.Add("SubCatagory", typeof(string));
            model.rateCardAU.Columns.Add("Tags", typeof(string));
            model.rateCardAU.Columns.Add("Unit", typeof(string));

            foreach (var meter in azureRateCard.Meters)
            {
                if (meter.Region.StartsWith("AU"))
                {
                    azureRateCardAU.Add(meter);
                    var effectivedate = meter.EffectiveDate.ToString();
                    var rates = (String.Join(", ", meter.Rates.ToArray()).ToString());
                    var tags = (String.Join(", ", meter.Tags.ToArray()).ToString());
                    model.rateCardAU.Rows.Add(meter.Category, effectivedate, meter.Id, meter.IncludedQuantity, meter.Name, rates, meter.Region, meter.Subcategory, tags, meter.Unit);
                }
            }

            model.offerCount = offers.TotalCount;
            model.getDate = DateTime.Now.ToLocalTime();
            model.rateCardAUCount = azureRateCardAU.Count();

            return View(model);
        }

        public ActionResult MSCSPCurrentInvoice()
        {
            IAggregatePartner partner = GetPartnerCenterTokenUsingAppCredentials();
            var model = new OfferView();
            model.officeLineItems = new DataTable();
            model.officeLineItems.Columns.Add("CustomerName");
            model.officeLineItems.Columns.Add("CustomerId");
            model.officeLineItems.Columns.Add("ChargeStartDate");
            model.officeLineItems.Columns.Add("ChargeEndDate");
            model.officeLineItems.Columns.Add("BillingProvider");
            model.officeLineItems.Columns.Add("ChargeType");
            model.officeLineItems.Columns.Add("BillingCycleType");
            model.officeLineItems.Columns.Add("OfferName");
            model.officeLineItems.Columns.Add("OfferId");
            model.officeLineItems.Columns.Add("serviceCost");
            model.azureLineItems = new DataTable();
            model.azureLineItems.Columns.Add("CustomerName");
            model.azureLineItems.Columns.Add("CustomerId");
            model.azureLineItems.Columns.Add("ChargeStartDate");
            model.azureLineItems.Columns.Add("ChargeEndDate");
            model.azureLineItems.Columns.Add("BillingProvider");
            model.azureLineItems.Columns.Add("ChargeType");
            model.azureLineItems.Columns.Add("BillingCycleType");
            model.azureLineItems.Columns.Add("ServiceName");
            model.azureLineItems.Columns.Add("Sku");
            model.azureLineItems.Columns.Add("pretaxCharges");
            model.azureDailyLineItems = new DataTable();
            model.azureDailyLineItems.Columns.Add("CustomerName");
            model.azureDailyLineItems.Columns.Add("CustomerId");
            model.azureDailyLineItems.Columns.Add("ChargeStartDate");
            model.azureDailyLineItems.Columns.Add("ChargeEndDate");
            model.azureDailyLineItems.Columns.Add("BillingProvider");
            model.azureDailyLineItems.Columns.Add("ConsumedQuantity");
            model.azureDailyLineItems.Columns.Add("BillingCycleType");
            model.azureDailyLineItems.Columns.Add("ServiceName");
            model.azureDailyLineItems.Columns.Add("ServiceType");
            model.azureDailyLineItems.Columns.Add("unit");

            // Get the last 5 invoices
            var pagedInvoiceCollection = partner.Invoices.Query(QueryFactory.Instance.BuildIndexedQuery(5, 0));

            // Select the latest invoice
            var latestInvoice = pagedInvoiceCollection.Items.First();
            model.currentCharges = latestInvoice.CurrencySymbol.ToString() + latestInvoice.TotalCharges.ToString() + "(" + latestInvoice.CurrencyCode + ")";
            
            var invoiceOperations = partner.Invoices.ById(latestInvoice.Id.ToString());
            var invoice = invoiceOperations.Get();

            model.officeCosts = 0;
            model.azureCosts = 0;
            model.internalUseAzureCosts = 0;

            foreach (var invoiceDetail in invoice.InvoiceDetails)
            {
                string BillingProvider = invoiceDetail.BillingProvider.ToString();
                string InvoiceLineItemType = invoiceDetail.InvoiceLineItemType.ToString();

                var invoiceLineItemsCollection = invoiceOperations.By(invoiceDetail.BillingProvider, invoiceDetail.InvoiceLineItemType).Get();
                var invoiceLineItemEnumerator = partner.Enumerators.InvoiceLineItems.Create(invoiceLineItemsCollection);

                if (BillingProvider == "Office")
                {
                    while (invoiceLineItemEnumerator.HasValue)
                    {
                        // invoiceLineItemEnumerator.Current contains a collection of line items.
                        model.officeUsage_itemCount = invoiceLineItemEnumerator.Current.TotalCount.ToString();

TDServicesApp/TDServicesApp/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TDServicesApp.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        [LayoutInjecter("_Layout")]
        public ActionResult SESCustomerPortal()
        {
            return View();
        }
    }
}

TDServicesApp/TDServicesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - TechData Australia - Services Web App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Following scripts are used for the Rainbow addon -->
    @Styles.Render("~/Scripts/rainbow-master/themes/css/blackboard.css")
    @Scripts.Render("~/Scripts/rainbow-master/dist/rainbow.js")
    @Scripts.Render("~/Scripts/rainbow-master/src/language/generic.js")
    @Scripts.Render("~/Scripts/rainbow-master/src/language/javascript.js")

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>

    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'13aaee93-4660-4b54-99a0-0454554851d7'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
 </head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" title="Tech Data" class="links">
                    <img src="~/Content/images/tdlogo.png" align="middle" height=50 alt="Tech Data" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="@Url.Action("Index", "Home")">
                            <span class="glyphicon glyphicon-home"></span>
                            Home
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Change Log", "ChangeLog", "Home")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="">
                            <span class="glyphicon glyphicon-pencil"></span>
                            Demo
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("SES Customer Portal", "SESCustomerPortal", "Demo")</li>
                        </ul>
                    </li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Demo"))
                    {
                        <li>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="">
                                <span class="glyphicon glyphicon-cloud"></span>
                                Cloud
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                @if (User.IsInRole("Admin"))
                                {
                                    <li>@Html.ActionLink("CSP - Current Invoice", "MSCSPCurrentInvoice", "Cloud")</li>
                                    <li>@Html.ActionLink("CSP - Customers", "MSCSPCustomers", "Cloud")</li>
                                    <li>@Html.ActionLink("CSP - Offer List", "MSCSPOffers", "Cloud")</li>
                                    <li>@Html.ActionLink("CSP - Rate Card", "MSCSPRateCard", "Cloud")</li>
                                    <li>@Html.ActionLink("CSP - Domain Availability Check", "MSCSPDomainAvailability", "Cloud")</li>
                                    <li>@Html.ActionLink("Microsoft Service Status", "MicrosoftServiceStatus", "Cloud")</li>
                                    <li>@Html.ActionLink("Partner Center Activity Logs", "MSCSPPartnerCenterActivityLogs", "Cloud")</li>
                                    <li>@Html.ActionLink("Partner Center to SEM Importer", "AzureCSPRISKU2SEM", "Cloud")</li>
                                }
                                else
                                {
                                    <li>@Html.ActionLink("Partner Center to SEM Importer", "AzureCSPRISKU2SEM", "Cloud")</li>
                                }
                            </ul>
                        </li>
                        if (User.IsInRole("Admin"))
                        {
                            <li>
                                <a class="dropdown-toggle" data-toggle="dropdown" href="">
                                    <span class="glyphicon glyphicon-paperclip"></span>
                                    Tools
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>@Html.ActionLink("Data Metering", "Index", "DataMetering")</li>
                                    <li>@Html.ActionLink("Backup Usage - Beta", "Index", "DPMetering")</li>
                                    <li>@Html.ActionLink("Asset Registry", "Index", "AssetReg")</li>
                                    <li>@Html.ActionLink("License Usage", "Index", "LicenseUsage")</li>
                                    <li>@Html.ActionLink("GAuth MFA Client", "GAuthMFAClient", "Cloud")</li>
                                </ul>
                            </li>
                        }
                    }

                    <li>
                        <a href="@Url.Action("Index", "Help")">
                            <span class="glyphicon glyphicon-heart"></span>
                            Help & Support
                        </a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> @Html.Encode(ViewBag.elapsedTime) seconds.</p>
            <p>&copy; @DateTime.Now.Year - TechData Australia</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

TDServicesApp/TDServicesApp/Views/Shared/_LayoutAssetReg.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Custom.css" rel="stylesheet" />
    <link href="~/Content/themes/base/all.css" rel="stylesheet">
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/themes/base/autocomplete.css" rel="stylesheet" />

    <!-- Used for Autocomplete -->
    <script src="~/Scripts/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js" type="text/javascript"></script>

    <script src="~/Scripts/bootstrap.js" type="text/javascript"></script>

    <!-- Simple Sidebar CSS -->
    <link href="~/Content/simple-sidebar.css" rel="stylesheet">

    <!-- Used for AJAX Async wait -->
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>@ViewBag.Title - TechData Australia - Services Web App</title>

    <style>
        .ui-autocomplete {
            position: absolute;
            cursor: default;
            z-index: 1001 !important
        }
    </style>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" title="Tech Data" class="links">
                    <img src="~/Content/images/tdlogo.png" align="middle" height=50 alt="Tech Data" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <span class="glyphicon glyphicon-home"></span>
                            Home
                        </a>
                    </li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Change Log", "ChangeLog", "Home")</li>
                    <li>@Html.ActionLink("Help & Support", "Index", "Help", new { area = "" }, null)</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="">
                                Tools
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Data Metering", "Index", "DataMetering")</li>
                                <li>@Html.ActionLink("Backup Usage", "Index", "DPMetering")</li>
                                <li>@Html.ActionLink("Asset Registry", "Index", "AssetReg")</li>
                                <li>@Html.ActionLink("License Usage", "Index", "LicenseUsage")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="wrapper" class="toggled">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        @Html.ActionLink("Asset Registry", "Index", "AssetReg")
                    </li>
                    <li>@Html.ActionLink("Search/Edit Machine", "SearchMachine", "AssetReg")</li>
                    <li>@Html.ActionLink("Search/Edit Customer", "SearchCustomer", "AssetReg")</li>
                    <li>@Html.ActionLink("Remote Connection", "SearchCustomerData", "AssetReg")</li>
                    <li>@Html.ActionLink("Add New Customer", "AddNewCustomer", "AssetReg")</li>
                    <li>@Html.ActionLink("Add Virtual Machine", "AddVirtual", "AssetReg")</li>
                    <li>@Html.ActionLink("Add Physical Asset", "AddServer", "AssetReg")</li>
                </ul>
            </div>
            <!-- /#sidebar-wrapper -->
            <!-- Page Content -->
            @*<div id="page-content-wrapper">*@
            @*<div class="container-fluid">*@ @*Enable this to have body content move with menu operations*@
            <div class="row">
                <div class="col-lg-12">
                    @RenderBody()
                </div>
            </div>
            @*</div>*@
            @*</div>*@
            <!-- /#page-content-wrapper -->
            <hr />
            <footer>
                <p> @Html.Encode(ViewBag.elapsedTime) seconds.</p>
                <p>&copy; @DateTime.Now.Year  - TechData Australia</p>
            </footer>
        </div>
        <!-- /#wrapper -->
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>

TDServicesApp/TDServicesApp/Views/Shared/_LayoutDPMetering.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Custom.css" rel="stylesheet" />
    <link href="~/Content/themes/base/all.css" rel="stylesheet">
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/themes/base/autocomplete.css" rel="stylesheet" />

    <!-- Used for Autocomplete -->
    <script src="~/Scripts/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js" type="text/javascript"></script>

    <script src="~/Scripts/bootstrap.js" type="text/javascript"></script>

    <!-- Simple Sidebar CSS -->
    <link href="~/Content/simple-sidebar.css" rel="stylesheet">

    <!-- Used for AJAX Async wait -->
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>@ViewBag.Title - TechData Australia - Services Web App</title>

    <style>
        .ui-autocomplete {
            position: absolute;
            cursor: default;
            z-index: 1001 !important
        }
    </style>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" title="Tech Data" class="links">
                    <img src="~/Content/images/tdlogo.png" align="middle" height=50 alt="Tech Data" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <span class="glyphicon glyphicon-home"></span>
                            Home
                        </a>
                    </li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Change Log", "ChangeLog", "Home")</li>
                    <li>@Html.ActionLink("Help & Support", "Index", "Help", new { area = "" }, null)</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="">
                                Tools
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Data Metering", "Index", "DataMetering")</li>
                                <li>@Html.ActionLink("Backup Usage", "Index", "DPMetering")</li>
                                <li>@Html.ActionLink("Asset Registry", "Index", "AssetReg")</li>
                                <li>@Html.ActionLink("License Usage", "Index", "LicenseUsage")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div id="wrapper" class="toggled">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li class="sidebar-brand">
                        @Html.ActionLink("Data Protection Metering", "Index", "DPMetering")
                    </li>
                    <li>@Html.ActionLink("Customer Usage", "CustUsage", "DPMetering")</li>
                    <li>@Html.ActionLink("SAP Export", "SAPExport", "DPMetering")</li>
                </ul>
            </div>
            <!-- /#sidebar-wrapper -->
            <!-- Page Content -->
            @*<div id="page-content-wrapper">*@
            @*<div class="container-fluid">*@ @*Enable this to have body content move with menu operations*@
            <div class="row">
                <div class="col-lg-12">
                    @RenderBody()
                </div>
            </div>
            @*</div>*@
            @*</div>*@
            <!-- /#page-content-wrapper -->
            <hr />
            <footer>
                <p> @Html.Encode(ViewBag.elapsedTime) seconds.</p>
                <p>&copy; @DateTime.Now.Year  - TechData Australia</p>
            </footer>
        </div>
        <!-- /#wrapper -->
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>