TDServicesApp/TDServicesApp/Controllers/DataMeteringController.cs
using System; // For system functions like Console.
using System.Collections.Generic; // For generic collections like List
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using TDServicesApp.Models;
using System.Diagnostics;
using System.Data.SqlClient;      // For the database connections and objects
using System.Threading.Tasks;
using System.Configuration;
using System.IO;
using Newtonsoft.Json;
using PagedList;

namespace TDServicesApp.Controllers
{
    public class LayoutInjecterAttribute : ActionFilterAttribute
    {
        private readonly string _masterName;
        public LayoutInjecterAttribute(string masterName)
        {
            _masterName = masterName;
        }

        public override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            base.OnActionExecuted(filterContext);
            var result = filterContext.Result as ViewResult;
            if (result != null)
            {
                result.MasterName = _masterName;
            }
        }
    }
    //public class DataMeteringController : Controller
    [Authorize(Roles = "Admin,Reseller,Customer")]
    public class DataMeteringController : GlobalController
    {
        // GET: DataMetering
        [LayoutInjecter("_LayoutSideMenu")]
        public ActionResult Index()
        {
            int WAN_Bandwidth = 45; //This is in MB/sec
            string tableName = DateTime.Now.ToString("MMMM");
            ViewBag.tableName = tableName;

            //Average throughput usage
            DataTable GetBandwidthUsage = new DataTable();
                try
                {
                    string query = "select * from qs_BandwidthUsage";
                    SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["NetflowDataConnectionString"].ConnectionString);
                    SqlCommand cmd = new SqlCommand(query, conn);
                    conn.Open();
                    SqlDataAdapter da = new SqlDataAdapter(cmd);
                    da.Fill(GetBandwidthUsage);
                    conn.Close();
                    da.Dispose();
                if (GetBandwidthUsage.Rows.Count > 0)
                    {
                        DataRow row = GetBandwidthUsage.Rows[0];

                        double average_inMbps = Convert.ToInt32(row["average_inMbps"]);
                        ViewBag.average_inMbps = average_inMbps;
                        double average_outMbps = Convert.ToInt32(row["average_outMbps"]);
                        ViewBag.average_outMbps = average_outMbps;
                        double total_Mbps = average_inMbps + average_outMbps;
                        ViewBag.total_Mbps = total_Mbps;
                        ViewBag.WAN_Bandwidth = WAN_Bandwidth;
                        double CapacityAvaliable = ((double)total_Mbps / (double)WAN_Bandwidth)*100;
                        CapacityAvaliable = (100 - CapacityAvaliable);
                        ViewBag.CapacityAvaliable = Math.Round(CapacityAvaliable);
                    }
                }
                catch
                {
                    ViewBag.average_inMbps = 0;
                    ViewBag.average_outMbps = 0;
                }

            //Average daily and forecast usage
            DataTable GetForecastUsage = new DataTable();
                try
                {
                    string query = "select * from qs_ForecastUsage";
                    SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["NetflowDataConnectionString"].ConnectionString);
                    SqlCommand cmd = new SqlCommand(query, conn);
                    conn.Open();
                    SqlDataAdapter da = new SqlDataAdapter(cmd);
                    da.Fill(GetForecastUsage);
                    conn.Close();
                    da.Dispose();
                    if (GetForecastUsage.Rows.Count > 0)
                    {
                        DataRow row = GetForecastUsage.Rows[0];
                        ViewBag.MonthForecast = row["MonthForecast"].ToString();
                        ViewBag.averageDaily_inGBytes = row["averageDaily_outGBytes"].ToString();
                        ViewBag.averageDaily_outGBytes = row["averageDaily_inGBytes"].ToString();
                    }
                }
                catch
                {
                    ViewBag.MonthForecast = "No data for this month!";
                }
            return View();
        }

        public List<CustomerModel> GetCustomers(string tableName)
        {
            List<CustomerModel> objList = new List<CustomerModel>();

            //Daily customer usage
            DataTable GetCustomers = new DataTable();
            using (var con = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["NetflowDataConnectionString"].ConnectionString))
            using (var cmd = new SqlCommand("usp_GetTotalUsageCust", con))
            using (var da = new SqlDataAdapter(cmd))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Month", tableName);
                da.Fill(GetCustomers);
            }

            objList.Add(new CustomerModel { Id = 0, CustomerName = "Select Customer" });

            int listId = 0;
            foreach (DataRow row in GetCustomers.Rows)
            {
                listId++;
                objList.Add(new CustomerModel { Id = listId, CustomerName = row["Customer Name"].ToString() });
            }

            return objList;
        } //Not tested as yet, can be used as initial customer filter for DataUsageReport. Uses CustomerModel class from DataMeteringModel.

        [LayoutInjecter("_LayoutSideMenu")]
        public ActionResult UsageCustomerDaily(string tableName, string customerName)
        {
            Stopwatch maintimer = new Stopwatch();
            maintimer.Start();

            if (!Request.Path.ToString().Contains("UsageCustomerDaily"))
            {
                return View("UsageCustomer");
            }

            //Initialise a new instance of an object for each model class
            var model = new DataMeteringModel();

            //Reassociate the model.CustomerName so we can use it in the View
            model.CustomerName = customerName;
            model.tableName = tableName;

            //Check if the table exists, else exit
            string tableCheck = "";
            using (var con = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["NetflowDataConnectionString"].ConnectionString))
            using (var cmd = new SqlCommand("usp_TableCheck", con))
            using (var da = new SqlDataAdapter(cmd))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@tableName", tableName);
                con.Open();
                var result = cmd.ExecuteScalar();
                con.Close();
                tableCheck = result.ToString();
            }
            if (tableCheck == "No")
            {
                ViewBag.Error = "Table does not exist!";
                return View();
            }

            //Daily customer usage
            DataTable GetTotalUsageCust = new DataTable();
            using (var con = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["NetflowDataConnectionString"].ConnectionString))
            using (var cmd = new SqlCommand("usp_GetTotalUsageCust", con))
            using (var da = new SqlDataAdapter(cmd))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Month", tableName);
                cmd.Parameters.AddWithValue("@CustomerName", customerName);
                da.Fill(GetTotalUsageCust);
            }
            model.totalUsageCustPerDay = GetTotalUsageCust;

            //Device based usage for customer
            DataTable totalUsagePerDevice = new DataTable();
            using (var con = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["NetflowDataConnectionString"].ConnectionString))
            using (var cmd = new SqlCommand("usp_GetDeviceTotalCust", con))
            using (var da = new SqlDataAdapter(cmd))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@Month", tableName);
                cmd.Parameters.AddWithValue("@CustomerName", customerName);
                da.Fill(totalUsagePerDevice);
            }
            model.totalUsagePerDevice = totalUsagePerDevice;

            //The portion of code is used to separate and serialise the data into JSON for CanvasJS
            DataTable inboundData = new DataTable();
            inboundData = GetTotalUsageCust.Copy();
            inboundData.Columns.Add("FormattedDT");
            foreach (DataRow row in inboundData.Rows)
            {
                row["FormattedDT"] = (Convert.ToDateTime(row["dt"]).ToString("yyyy, MM, dd, HH"));
            }
            inboundData.Columns.Remove("dt");
            inboundData.Columns.Remove("total_outGBytes");
            ViewBag.DataPoints1 = JsonConvert.SerializeObject(inboundData);
            DataTable outboundData = new DataTable();
            outboundData = GetTotalUsageCust.Copy();
            outboundData.Columns.Add("FormattedDT");
            foreach (DataRow row in outboundData.Rows)
            {
                row["FormattedDT"] = (Convert.ToDateTime(row["dt"]).ToString("yyyy, MM, dd, HH"));
            }
            outboundData.Columns.Remove("dt");
            outboundData.Columns.Remove("total_inGBytes");
            ViewBag.DataPoints2 = JsonConvert.SerializeObject(outboundData);

            maintimer.Stop();
            model.maintimerduration = maintimer.Elapsed.Milliseconds;

            return View(model);

TDServicesApp/TDServicesApp/Views/DataMetering/DataUsageReport.cshtml
@using System.Data;
@using System.Globalization;
@model TDServicesApp.Models.DataMeteringModel

@{
    ViewBag.Title = "Data Usage Report";
}

<h2>Data Usage Report</h2>

@using (Html.BeginForm())
{
    if (ViewBag.Error != null)
    {
        <h3>Error - @ViewBag.Error</h3>
    }
    <p>Select the month and year to export data for</p>
    @Html.DropDownList("Year", Enumerable.Range(DateTime.Now.Year, 10).Select(x => new SelectListItem { Text = x.ToString() }), "Year")
    @Html.DropDownList("Month", DateTimeFormatInfo.InvariantInfo.MonthNames.Where(m => !String.IsNullOrEmpty(m)).Select((monthName, index) => new SelectListItem { Text = monthName }), "Month")
    <input type="submit" />
}

@if (Model != null)
{
    <h4>Netflow Stats</h4>
    <p>Total netflow records - @Model.netflowrecords</p>

    <h4>Data Stats</h4>
    <p>Total TB transferred inbound - @Model.totalindata</p>
    <p>Total TB transferred outbound - @Model.totaloutdata</p>
    <p>Total TB transferred - @Model.totaldata</p>

    <h4>Debug - Timers (ms)</h4>
    <p>Total time for controller to complete - @Model.maintimerduration</p>

    <h3>General Usage Report</h3>
    <table id="myTable" border="1">
        <tr>
            @foreach (DataColumn dc in (Model.generalUsageReport as DataTable).Columns)
            {
                <th>@dc.ColumnName</th>
            }
        </tr>
        @foreach (DataRow dr in (Model.generalUsageReport as DataTable).Rows)
        {
            <tr>
                <td align="center">
                    @dr["IPAddress"]
                </td>
                <td align="center">
                    @dr["MachineID"]
                </td>
                <td align="center">
                    @dr["Machine Name"]
                </td>
                <td align="center">
                    @dr["CustomerNumber"]
                </td>
                <td align="center">
                    @dr["Customer Name"]
                </td>
                <td align="center">
                    @dr["contract_num_sap"]
                </td>
                <td align="center">
                    @dr["inbytes"]
                </td>
                <td align="center">
                    @dr["outbytes"]
                </td>
                <td align="center">
                    @dr["dt"]
                </td>
            </tr>
        }
    </table>
}

TDServicesApp/TDServicesApp/Views/DataMetering/DataUsageReportView.cshtml
@model TDServicesApp.Models.DataMeteringModel
@*@model PagedList.IPagedList<TDServicesApp.Models.DataMeteringModel>*@
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Data Usage Report";
}

<h2>Data Usage Report</h2>
<p>As the results are granular (i.e. per hour) searching can take time, additionally the application may crash. If this happens reload the page, this will be addressed in a later revision.</p>

@if (Model != null)
{
    using (Html.BeginForm("DataUsageReportView", "DataMetering", FormMethod.Get))
    {
        <p>
            @*Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)*@
            Find by keyword: @Html.TextBox("SearchString", ViewBag.currentFilter as string)
            Viewing month: @Html.TextBox("TableName", ViewBag.tableName as string, new { @readonly = "true" })
            <input type="submit" value="Search" />
        </p>
    }

    //if (Request.UrlReferrer.ToString().Contains("DataUsageReport"))
    if (Request.UrlReferrer.LocalPath.ToString().Equals("/DataMetering/DataUsageReport"))
    {
        <h4>Netflow Stats</h4>
        <p>Total netflow records - @Model.netflowrecords</p>

        <h4>Data Stats</h4>
        <p>Total TB transferred inbound - @Model.totalindata</p>
        <p>Total TB transferred outbound - @Model.totaloutdata</p>
        <p>Total TB transferred - @Model.totaldata</p>

        <h4>Debug - Timers (ms)</h4>
        <p>Total time for controller to complete - @Model.maintimerduration</p>

        <h3>General Usage Report</h3>
    }

    <table id="myTable" border="1">
        <tr>
            <th>
                IP Address
            </th>
            <th>
                Machine ID
            </th>
            <th>
                Machine Name
            </th>
            <th>
                Customer ID
            </th>
            <th>
                @*@Html.ActionLink("Customer Name", "DataUsageReportView", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })*@
                @Html.ActionLink("Customer Name", "DataUsageReportView", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter, tableName = ViewBag.TableName })
            </th>
            <th>
                Contract Number
            </th>
            <th>
                Bytes (Inbound)
            </th>
            <th>
                Bytes (Outbound)
            </th>
            <th>
                Date and Time
            </th>
        </tr>
        @foreach (var item in Model.mypagedList)
        {
            <tr>
                <td>
                    @item[0]
                </td>
                <td>
                    @item[1]
                </td>
                <td>
                    @item[2]
                </td>
                <td>
                    @item[3]
                </td>
                <td>
                    @item[4]
                </td>
                <td>
                    @item[5]
                </td>
                <td>
                    @item[6]
                </td>
                <td>
                    @item[7]
                </td>
                <td>
                    @item[8]
                </td>
            </tr>
        }
    </table>
    <br />
}
Page @((Model.mypagedList as PagedList.IPagedList).PageCount < (Model.mypagedList as PagedList.IPagedList).PageNumber ? 0 : (Model.mypagedList as PagedList.IPagedList).PageNumber) of @((Model.mypagedList as PagedList.IPagedList).PageCount)

@Html.PagedListPager((Model.mypagedList as PagedList.IPagedList), page => Url.Action("DataUsageReportView", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, tableName = ViewBag.TableName }))

TDServicesApp/TDServicesApp/Views/DataMetering/DataUsageSAPExport.cshtml
@using System.Globalization;
@model TDServicesApp.Models.DataUsageSAPExportModel

@{
    ViewBag.Title = "DataUsageSAPExport";
}

<h2>Data Usage - SAP Export</h2>

@using (Html.BeginForm())
{
    if(ViewBag.Error != null)
    {
        <h3>Error - @ViewBag.Error</h3>
    }
    <p>Select the month and year to export data for</p>
    @Html.DropDownList("Year", Enumerable.Range(DateTime.Now.Year, 10).Select(x => new SelectListItem { Text = x.ToString() }), "Year")
    @Html.DropDownList("Month", DateTimeFormatInfo.InvariantInfo.MonthNames.Where(m => !String.IsNullOrEmpty(m)).Select((monthName, index) => new SelectListItem { Text = monthName }), "Month")
    <input type="submit" />
}

TDServicesApp/TDServicesApp/Views/DataMetering/Index.cshtml
@model TDServicesApp.Models.DataMeteringModel

@{
    ViewBag.Title = "Index";
}

<h1>Data Usage Reports Navigation</h1>
<p>Use the menu on the left to navigate to corresponding pages.</p>
<a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<!-- Menu Toggle Script -->
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>

<div class="row">
    <div class="col-md-4">
        <h4>Average Link Utilisation</h4>
        @if (ViewBag.average_inMbps == 0 || ViewBag.average_outMbps == 0)
        {
            <p>No data avaliable to forecast usage!</p>
        }
        else
        {
            <p>Inbound - @ViewBag.average_inMbps MB/sec</p>
            <p>Outbound - @ViewBag.average_outMbps MB/sec</p>
            <p>Total Used Bandwidth - @ViewBag.total_Mbps MB/sec</p>
            <p>Total Avaliable Bandwidth - @ViewBag.WAN_Bandwidth MB/sec</p>
            <p>Bandwidth Avaliable - @ViewBag.CapacityAvaliable %</p>

        }
</div>
    <div class="col-md-4">
        <h4>Projected Usage for @ViewBag.TableName</h4>
        <p>Inbound/Day - @ViewBag.averageDaily_inGBytes GB</p>
        <p>Outbound/Day - @ViewBag.averageDaily_outGBytes GB</p>
        <p>@ViewBag.TableName Total - @ViewBag.MonthForecast GB</p>
    </div>
</div>

TDServicesApp/TDServicesApp/Views/DataMetering/InvalidCustomer.cshtml
@using System.Data;
@using System.Globalization;
@model TDServicesApp.Models.DataMeteringModel

@{
    ViewBag.Title = "Invalid Customer Records";
}

<h2>Invalid Customer Records</h2>

@using (Html.BeginForm())
{
    if (ViewBag.Error != null)
    {
        <h3>Error - @ViewBag.Error</h3>
    }
    <p>Select the month and year to export data for</p>
    @Html.DropDownList("Year", Enumerable.Range(DateTime.Now.Year, 10).Select(x => new SelectListItem { Text = x.ToString() }), "Year")
    @Html.DropDownList("Month", DateTimeFormatInfo.InvariantInfo.MonthNames.Where(m => !String.IsNullOrEmpty(m)).Select((monthName, index) => new SelectListItem { Text = monthName }), "Month")
    <input type="submit" />
}

@if (Model != null)
{
    <h4>Debug - Timers (ms)</h4>
    <p>Total time for controller to complete - @Model.maintimerduration</p>

    <h3>Invalid Customer Entries Found</h3>
    <table id="myTable" border="1">
        <tr>
            <th>Customer Number</th>
            <th>Customer Name</th>
            <th>Machine Name</th>
            <th>Inbound (GB)</th>
            <th>Outbound (GB)</th>
            <th>Total (GB)</th>
        </tr>
        @foreach (DataRow dr in (Model.totalUsagePerCust as DataTable).Rows)
        {
            <tr>
                <td align="center">
                    @dr["CustomerNumber"]
                </td>
                <td align="center">
                    @dr["Customer Name"]
                </td>
                <td align="center">
                    @dr["Machine Name"]
                </td>
                <td align="center">
                    @dr["total_inGBytes"]
                </td>
                <td align="center">
                    @dr["total_outGBytes"]
                </td>
                <td align="center">
                    @dr["total_GBytes"]
                </td>
            </tr>
        }
    </table>
}

TDServicesApp/TDServicesApp/Views/DataMetering/NetflowDBStats.cshtml
@using System.Data;
@model TDServicesApp.Models.NetflowDBStatsModel

@{
    ViewBag.Title = "NetflowDBStats";
}

<h2>Database Stats</h2>

@if (Model != null)
{
    <h3>SQL Database Statistics</h3>
    <table id="myTable" border="1">
        <tr>
            @foreach (DataColumn dc in (Model.sqltablesize as DataTable).Columns)
            {
                <th>@dc.ColumnName</th>
            }
        </tr>
        @foreach (DataRow dr in (Model.sqltablesize as DataTable).Rows)
        {
            <tr>
                <td align="center">
                    @dr["DB Name"]
                </td>
                <td align="center">
                    @dr["File Type"]
                </td>
                <td align="center">
                    @dr["Size in GBytes"]
                </td>
            </tr>
        }
    </table>
}
else
{
    <h3>SQL Database Statistics</h3>
    <p>An error occured - @Model.queryErrorMessage</p>
}

TDServicesApp/TDServicesApp/Views/DataMetering/UsageCustomer.cshtml
@using System.Data;
@using System.Globalization;
@model TDServicesApp.Models.DataMeteringModel

@{
    ViewBag.Title = "UsageCustomer";
}

<h2>Usage per Customer</h2>

@using (Html.BeginForm())
{
    if (ViewBag.Error != null)
    {
        <h3>Error - @ViewBag.Error</h3>
    }
    <p>Select the month and year to export data for</p>
    @Html.DropDownList("Year", Enumerable.Range(DateTime.Now.Year, 10).Select(x => new SelectListItem { Text = x.ToString() }), "Year")
    @Html.DropDownList("Month", DateTimeFormatInfo.InvariantInfo.MonthNames.Where(m => !String.IsNullOrEmpty(m)).Select((monthName, index) => new SelectListItem { Text = monthName }), "Month")
    <input type="submit" />
}

@if (Model != null)
{
    <h4>Customer Stats</h4>
    <p>Total number of customers - @Model.resultsTableCustCount</p>

    <h4>Debug - Timers (ms)</h4>
    <p>Total time for controller to complete - @Model.maintimerduration</p>

    <h3>Usage/Customer</h3>
    <table id="myTable" border="1">
        <tr>
            @foreach (DataColumn dc in (Model.totalUsagePerCust as DataTable).Columns)
            {
                <th>@dc.ColumnName</th>
            }
        </tr>
        @foreach (DataRow dr in (Model.totalUsagePerCust as DataTable).Rows)
        {
            <tr>
                <td align="center">
                    @dr["CustomerNumber"]
                </td>
                <td align="center">
                    @Ajax.ActionLink(@dr["Customer Name"].ToString(), "UsageCustomerDaily", "DataMetering", new { customerName = @dr["Customer Name"], tableName = Model.tableName }, new AjaxOptions { HttpMethod = "Post" })
                    @*@dr["Customer Name"]*@
                </td>
                <td align="center">
                    @dr["total_inGBytes"]
                </td>
                <td align="center">
                    @dr["total_outGBytes"]
                </td>
                <td align="center">
                    @dr["total_GBytes"]
                </td>
            </tr>
        }
    </table>
}

TDServicesApp/TDServicesApp/Views/DataMetering/UsageCustomerDaily.cshtml
@using System.Data;
@using System.Globalization;
@model TDServicesApp.Models.DataMeteringModel

@{
    ViewBag.Title = "Customer Usage per Day";
}

@if (Model != null)
{
    <div id="chartContainer" style="height: 400px; width: 100%;"></div>
    <script type="text/javascript">
        var result1 = @Html.Raw(ViewBag.DataPoints1);
        var DataPoints1 =[];
	    var i = 0;
        for (i = 0; i < result1.length; i++){
            var fdttemp = result1[i].FormattedDT;
            var fdtsplit = fdttemp.split(",");
            var fdt = new Date(fdtsplit[0], fdtsplit[1] - 1, fdtsplit[2],fdtsplit[3]);
            DataPoints1.push({
                x: fdt,
                y: result1[i].total_inGBytes
            });
        };
        var result2 = @Html.Raw(ViewBag.DataPoints2);
        var DataPoints2 =[];
	    var i = 0;
        for (i = 0; i < result2.length; i++){
            var fdttemp = result2[i].FormattedDT;
            var fdtsplit = fdttemp.split(",");
            var fdt = new Date(fdtsplit[0], fdtsplit[1] - 1, fdtsplit[2],fdtsplit[3]);
            DataPoints2.push({
                x: fdt,
                y: result2[i].total_outGBytes
            });
        };
        window.onload = function () {
            var chart = new CanvasJS.Chart("chartContainer",
                {
                    title: {
                        text: "Usage per Day for @Model.CustomerName",
                        fontWeight: "normal",
                        fontSize: 30,
                        fontFamily: "Arial"
                    },
                    toolTip: {
                        content: "{y} {name} | {x} {value}",
                        animationEnabled: true
                    },
                    axisX: {
                        lineColor: "#4F81BC",
                        tickColor: "#4F81BC",
                        labelFontColor: "#4F81BC",
                        titleFontColor: "#4F81BC",
                        lineThickness: 2,
                    },
                    axisY: {
                        title: "Data Transferred (GBytes)",
                        lineColor: "#C0504E",
                        tickColor: "#C0504E",
                        labelFontColor: "#C0504E",
                        titleFontColor: "#C0504E",
                        lineThickness: 2,
                    },
                    data: [{
                        type: "column",
                        name: "GBytes",
                        legendText: "Inbound",
                        showInLegend: true,
                        dataPoints: DataPoints1
                    },
                    {
                        type: "column",
                        name: "GBytes",
                        legendText: "Outbound",
                        showInLegend: true,
                        dataPoints: DataPoints2
                    }],
                });
            chart.render();
        }
    </script>

    <table>
        <tr>
            @foreach (DataColumn dc in (Model.totalUsagePerDevice as DataTable).Columns)
            {
                <th>@dc.ColumnName</th>
            }
        </tr>
        @foreach (DataRow dr in (Model.totalUsagePerDevice as DataTable).Rows)
        {
            <tr>
                <td align="center">
                    @Ajax.ActionLink(@dr["Machine Name"].ToString(), "UsageDeviceDaily", "DataMetering", new { deviceName = @dr["Machine Name"], tableName = Model.tableName, customerName = Model.CustomerName }, new AjaxOptions { HttpMethod = "Post" })
                </td>
                <td align="center">
                    @dr["total_inGBytes"]
                </td>
                <td align="center">
                    @dr["total_outGBytes"]
                </td>
            </tr>
        }
    </table>
    <table id="myTable" border="1">
        <tr>
            @foreach (DataColumn dc in (Model.totalUsageCustPerDay as DataTable).Columns)
            {
                <th>@dc.ColumnName</th>
            }
        </tr>
        @foreach (DataRow dr in (Model.totalUsageCustPerDay as DataTable).Rows)
        {
            <tr>
                <td align="center">
                    @dr["total_inGBytes"]
                </td>
                <td align="center">
                    @dr["total_outGBytes"]
                </td>
                <td align="center">
                    @dr["dt"]
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>Something happened and we are not able to display the data.</p>
}

TDServicesApp/TDServicesApp/Views/DataMetering/UsageDaily.cshtml
@using System.Data;
@using System.Globalization;
@model TDServicesApp.Models.DataMeteringModel

@{
    ViewBag.Title = "UsageDaily";
}

<h2>Usage per Day</h2>

@using (Ajax.BeginForm("UsageDailyReportGen", "DataMetering", new AjaxOptions { UpdateTargetId = "result", LoadingElementId = "loading",  }))
{
    <p>Select the month and year to export data for</p>
    @Html.DropDownList("Year", Enumerable.Range(DateTime.Now.Year, 1).Select(x => new SelectListItem { Text = x.ToString() }), "Year")
    @Html.DropDownList("Month", DateTimeFormatInfo.InvariantInfo.MonthNames.Where(m => !String.IsNullOrEmpty(m)).Select((monthName, index) => new SelectListItem { Text = monthName }), "Month")
    <input type="submit" />
    <br />
}

<div id="loading" style="display:none;">
    <h3><img src="~/Content/images/ajax-loader.gif" />Generating Report... This will take a few minutes.</h3>
</div>
<div id="result" style=""></div>